### PR TITLE
Restructuring in the devpack

### PR DESCRIPTION
**Pull request by csmuller**
Two classes that belong into the `contracts` package where in the wrong package. I moved those.
Additionally, i moved all classes that define constants into a `constants` package. What's your opinion on this change?

### CODE REVIEW

**Comment by gsmachado** [comment]
I'm fine with these changes! Actually, I think it improves overall code organization.

However, I need to understand why classes such as `compiler/src/test/java/io/neow3j/compiler/Main.java`, `compiler/src/test/java/io/neow3j/compiler/MainCompileAndDeploy.java`, and `compiler/src/test/java/io/neow3j/compiler/MainPrintOpcodes.java` were added within this PR... from where those classes got pulled from?

**Comment by csmuller** [comment]
> However, I need to understand why classes such as `compiler/src/test/java/io/neow3j/compiler/Main.java`, `compiler/src/test/java/io/neow3j/compiler/MainCompileAndDeploy.java`, and `compiler/src/test/java/io/neow3j/compiler/MainPrintOpcodes.java` were added within this PR... from where those classes got pulled from?

🙄 those are not meant to be there. I just always had them in my workspace. Was only a question of time till I unintentionally commit them.

**Comment by gsmachado** [comment]
@csmuller These files are pretty useful, mainly for testing or to demo things (also, to reproduce issues).

Can you add those files somewhere else? Do you have any suggestions on where to add them?

**Comment by csmuller** [comment]
> Can you add those files somewhere else? Do you have any suggestions on where to add them?

Yes, to the gitignore ;)

**Comment by gsmachado** [comment]
> Yes, to the gitignore ;)

lol. Alright.. no worries. I can always come to this PR and copy and paste the files. 😅

**Pull request merged**
