### PR TITLE
Hotfixes for 3.14.0 release

### PR DESCRIPTION
**Pull request by csmuller**

### CODE REVIEW

**Comment by gsmachado** [comment]
maybe set the version in `build.gradle` to `3.14.1`? 😄

**Comment by gsmachado** [comment]
Is anything else missing to change from draft to a "ready to review" PR?

**Comment by csmuller** [comment]
> Is anything else missing to change from draft to a "ready to review" PR?

I will update the test-tools to the newest neo-express version that was released end of last week. Then we can review the PR.

**Review by gsmachado — APPROVED** [review]
Lots of improvements. 😄 
Let's go! 🚀

**Pull request merged**
