### PR TITLE
Support placeholder substitution in devpack tests

### PR DESCRIPTION
**Pull request by csmuller**

### CODE REVIEW

**Comment by csmuller** [comment]
- [ ] Adapt neow3j documentation on devpack-test.
- [ ] Document placeholder feature (it's not in the docs yet).

**Comment by gsmachado** [comment]
I have a question: the placeholder MUST be of a specific format? Like "<SOMETHING>"? Or can it be whatever string the user sets?

I just ask this because usually is `${something}` (in many languages, tools, e.g., Spring, etc). Just asking.

**Comment by csmuller** [comment]
> I have a question: the placeholder MUST be of a specific format? Like ""? Or can it be whatever string the user sets?

It can be of any format.

**Review by gsmachado — APPROVED** [review]
👍 fine for me.

**Comment by gsmachado** [comment]
> * [ ]  Adapt neow3j documentation on devpack-test.
> * [ ]  Document placeholder feature (it's not in the docs yet).

should we wait to merge until these ☝️ tasks get finalized?

**Pull request merged**
