### PR TITLE
Fix compiler and compiler tests

### PR DESCRIPTION
**Pull request by csmuller**

### CODE REVIEW

**Comment by csmuller** [comment]
The rest of the integration tests will be fixed when introducing the LedgerContract to the devpack.

**Review by gsmachado — APPROVED** [review]
Cool! Ready to go from my side. 🚀

**Comment by gsmachado** [comment]
> The rest of the integration tests will be fixed when introducing the LedgerContract to the devpack.

But those test fixes (the remaining ones) should be fixed part of the other issues (#390 #412), right?

**Comment by csmuller** [comment]
> But those test fixes (the remaining ones) should be fixed part of the other issues (#390 #412), right?

Yes.

**Pull request merged**
