### PR TITLE
Transaction tracking

### LINKED ISSUE #96: Transaction tracking
As a developer I want to have a convenient way to track an issued transaction. It should inform me once the transaction is persisted in a block and give me easy access to its application log.

### PR DESCRIPTION
**Pull request by mialbu**
Closes #96

### CODE REVIEW

**Review by gsmachado — APPROVED** [review]
@csmuller nice and elegant solution with the `.takeUntil()` Rx method! Cool. 💯

**Comment by gsmachado** [comment]
@csmuller is this still a draft?

**Comment by csmuller** [comment]
> @csmuller is this still a draft?

@mialbu has dome additions he will commit soon.

**Comment by mialbu** [comment]
> @csmuller is this still a draft?

I'll notify you shortly.

**Pull request merged**
